include: "rules/common.smk"
include: "rules/build_refgenomes.smk"
include: "rules/align_reads.smk"

configfile: "config/config.yaml"

rule all:
    input:
        "results/stats/samples.mapping.flagstat",
        "results/coverage/infref_genome_count.tsv",
        "results/coverage/infref_genome_depth.tsv",
        "results/coverage/infref_genome_gene_coverage.gct",
        "results/coverage/infref_genome_CDS_coverage.gct"
