include: "rules/build_refgenomes.smk"

configfile: "config.yaml"
refgenomes_dir = config["refgenomes_dir"]

rule all:
    input:
        "resources/ref/HBV_refgenomes_dup_BOWTIE2",
        "resources/ref/HBV_allgenomes.fasta",
        blastdb_filenames
