
version: 2

conda:
    environment: envs/environment.yml


# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

build:
   image: latest

# This part is necessary otherwise the project is not built
python:
   version: 3.7
   install:
      - method: pip
        path: .
        
# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
    include: all
