## use either way to indicate input files: either sample_annotation, or biokit_outdir
## sample_annotation should be a tab-delimited file containing at least four columns (#ID, GROUP, FASTQ1, FASTQ2)
sample_annotation: /pstore/data/biomics/_pre_portfolio/_RPF/MiladAdibi/HBVouroboros/HBVouroboros/RNAsim2/output/sampleAnnotation
biokit_outdir: None

## 3. options for read trimming with Trimmomatic
trim_reads: False
illumina_clip_file: 'resources/trim_reads/primers.fasta'
illumina_clip_opts: ':2:30:10:2:keepBothReads'
# trimmomatic steps (excluding ILLUMINACLIP)
trimmomatic_steps: 'LEADING:20 TRAILING:20 SLIDINGWINDOW:4:15 MINLEN:35 CROP:140'

## Run modes
doInputRef: True
inputRef: 'gnl|hbvnuc|AB064313_FT00000_C-G'
doPerSamp: True


