## use either way to indicate input files: either sample_annotation, or biokit_outdir
## sample_annotation should be a tab-delimited file containing at least four columns (#ID, GROUP, FASTQ1, FASTQ2)
sample_annotation: trimmed_sampleAnnotation
