name: RNAsim2
channels:
  - bioconda
  - conda-forge
dependencies:
  - python =3.7
  - requests
  - biopython
  - snakemake >=3.5
  - star =2.7.3a
  - bowtie2 =2.3.5
  - samtools =1.10
  - bedtools =2.29
  - pandas
  - blast
  - bcbio-gff
  - pytest
  - varscan
