name: HBVouroboros
channels:
  - bioconda
  - conda-forge
dependencies:
  - python =3.7
  - requests
  - biopython
  - snakemake >=3.5
  - star =2.7
  - bowtie2 =2.3
  - samtools =1.10
  - bedtools =2.29
  - pandas
  - trinity
  - blast
  - bcbio-gff
