name: HBVouroboros
channels:
  - bioconda
  - conda-forge
dependencies:
  - python =3.7
  - requests
  - biopython
  - snakemake >=5.3
  - star =2.7
  - bowtie2 =2.3
  - samtools =1.10
  - bedtools =2.29
  - fastqc=0.11.9=0
  - multiqc=1.8=py_1
  - pandas
  - trinity
  - blast
  - bcbio-gff
  - freebayes
