
rule star_index:
    input:
        fasta = "test-dupconc.fasta"
    output:
        directory("test-dupconc")
    message:
        "Generating STAR index"
    threads:
        1
    params:
        extra = ""
    log:
        "logs/star_index_test-dupconc.log"
    wrapper:
        "0.49.0/bio/star/index"
