import prepare_HBV_refgenomes as ref

localrules: download_HBV_refgenomes

rule all:
    input: "HBV_refgenomes_dup"

rule download_HBV_refgenomes:
    output:
        "HBV_refgenomes.fasta"
    log:
        "logs/HBV_refgenomes.log"
    run:
        ref.download_HBV_refgenomes("HBV_refgenomes.fasta")

rule HBV_refgenomes_dup:
    input:
        fasta="HBV_refgenomes.fasta"
    output:
        fasta="HBV_refgenomes_dup.fasta"
    log:
        "logs/HBV_refgenomes_dup.log"
    run:
        ref.dup_and_conc(input.fasta, output.fasta)

rule star_index:
    input:
        fasta = "HBV_refgenomes_dup.fasta"
    output:
        directory("HBV_refgenomes_dup")
    message:
        "Generating STAR index"
    threads:
        1
    params:
        extra = ""
    log:
        "logs/star_index_HBV_refgenomes_dup.log"
    wrapper:
        "0.49.0/bio/star/index"
