name: Python Package using Conda

on: [push]

jobs:
  pytest_pipeline:
    name: setup_env_pytest
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: initialize conda environment
        uses: conda-incubator/setup-miniconda@v2

      - name: create conda environment
        run: |
          conda install -c conda-forge mamba
          mamba init
          # reload .bashrc config for current bash terminal
          source ~/.bashrc
          mamba env create -f envs/environment.yml

      - name: run pytest
        run: |
          conda activate HBVouroboros
          pytest -s
