name: Python Package using Conda

name: Python Package using Conda

on: [push]

jobs:
  example-7:
    name: Ex7 Explicit
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: explicit-env
          environment-file: spec_file.txt
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
